

services:
  shovel_api:
    build: .
    ports:
      - "3010:3010"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
    command: yarn start:dev

  mongo:
    image: mongo:6
    container_name: shovel_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
